export const TRAPS_API_CALL_START = "TRAPS_API_CALL_START";
export const TRAPS_API_CALL_SUCCSES = "TRAPS_API_CALL_SUCCSES";
export const TRAPS_API_CALL_FAILURE = "TRAPS_API_CALL_FAILURE";
export const SEARCH_TRAPS = "SEARCH_TRAPS";
