export const BLOCK_API_CALL_START = "BLOCK_API_CALL_START";
export const BLOCK_API_CALL_SUCCSES = "BLOCK_API_CALL_SUCCSES";
export const BLOCK_API_CALL_FAILURE = "BLOCK_API_CALL_FAILURE";
export const SEARCH_BLOCK = "SEARCH_BLOCK";
